version: '3'

services:
  db:
    container_name: postgres
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
